name: CI

on:
  push:
    branches-ignore: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: '16'
      - name: Install dependencies backend
        run: |
          cd server
          npm install
      - name: Test backend
        run: |
          cd server
          npm run test-coverage
        env:
          TEST_DATABASE_URL: postgres://test:test@localhost:${{ job.services.postgres.ports['5432'] }}/test
          SECRET: testkey
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
      - name: Install dependencies frontend
        run: |
          cd client
          npm install
      - name: Check style - Backend
        run: |
          cd server
          npm run eslint
      - name: Check style - Frontend
        run: |
          cd client
          npm run eslint
      - name: open backend for e2e-tests
        run: |
          cd server
          npm run start:test &
          sleep 10
        env:
          TEST_DATABASE_URL: postgres://test:test@localhost:${{ job.services.postgres.ports['5432'] }}/test
          SECRET: testkey
      - name: open frontend for e2e-tests
        run: |
          cd client 
          npm run start &
          sleep 10
      - name: E2E tests
        run: cd client && npm run test:e2e
      
