name: main.yml

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: '20'
      - name: Install dependencies frontend
        run: |
          cd client
          npm install
      - name: Install dependencies backend
        run: |
          cd server
          npm install
      - name: Check style
        run: |
          cd server
          npm run eslint
          cd ..
          cd client
          npm run eslint
      - name: open backend for e2e-tests
        run: |
          cd server
          npm run start:test &
          sleep 10
        env:
          TEST_DATABASE_URL: postgres://test:test@localhost:${{ job.services.postgres.ports['5432'] }}/test
          DATABASE_URL: postgres://test:test@localhost:${{ job.services.postgres.ports['5432'] }}/test
          SECRET: testkey
      - name: open frontend for e2e-tests
        run: |
          cd client 
          npm run start &
          sleep 10
      - name: E2E tests
        run: cd client && npm run test:e2e
      