name: Automated tests

on:
  push:
    branches-ignore: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: '18'   
      - name: Install dependencies backend
        run: |
          cd server
          npm ci
      - name: Check style - Backend
        run: |
          cd server
          npm run eslint
      - name: Test backend
        run: |
          cd server
          npm run test-coverage
        env:
          TEST_DATABASE_URL: postgres://test:test@localhost:${{ job.services.postgres.ports['5432'] }}/test
          SECRET: testkey
          EMAIL_USER: ${{ secrets.EMAIL_USER}}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD}}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST}}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT}}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
      - name: Install dependencies frontend
        run: |
          cd client
          npm ci
      - name: Check style - Frontend
        run: |
          cd client
          npm run eslint   
      - name: Build frontend
        run: |
          cd client
          npm run build
      - name: Copy build folder to server
        run: |
          cp -R client/build server/build
      - name: open backend for e2e-tests
        run: |
          cd server
          npm run start:test &
          sleep 10
        env:
          TEST_DATABASE_URL: postgres://test:test@localhost:${{ job.services.postgres.ports['5432'] }}/test
          SECRET: testkey
          EMAIL_USER: ${{ secrets.EMAIL_USER}}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD}}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST}}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT}}
      - name: E2E tests
        run: cd client && npm run test:e2e
